### PR TITLE
Ability to chose what model to target.

### PR DESCRIPTION
**Pull request by lpurdy01**
Here is a better version of adding the --model option. For issue #67 .

It also adds a "DEFAULT_MODEL" option to the configuration file.

### CODE REVIEW

**Comment by carterprince** [comment]
This project plus GPT-4 is a truly a force to be reckoned with.

**Review by fmerenda — APPROVED** [review]

**Comment by lpurdy01** [comment]
@TheR1D Could we have a `beta` branch? Somewhere where we can play with the new systems without having to wait for them to be released to public? 

https://github.com/TheR1D/shell_gpt/pull/92#issuecomment-1493373872

**Comment by Kreijstal** [comment]
why isn't this merged yet?

**Comment by TheR1D** [comment]
Currently we are having 2 or 3 releases per week which is a lot. I don't think we will be able to maintain beta branch, it will be out of sync in just couple of days.

**Comment by TheR1D** [comment]
@Kreijstal @lpurdy01 @carterprince If you guys have access to GPT-4 beta, please confirm it works: https://github.com/TheR1D/shell_gpt/pull/151

**Comment by TheR1D** [comment]
https://github.com/TheR1D/shell_gpt/pull/151

**Pull request closed without merging**
