### PR TITLE
feat: get api key from OPENAI_API_KEY environment variable

### PR DESCRIPTION
**Pull request by loiccoyle**
Try to get the api key from the OPENAI_API_KEY environment variable before prompting user. 

This also avoids storing active api keys in unencrypted text files.

### CODE REVIEW

**Comment by loiccoyle** [comment]
Yeah that's the point, if you read from environment variables, you don't have to write it to file an unencrypted file, which is the current behaviour.

**Comment by TheR1D** [comment]
Hi @loiccoyle, thank you for the PR. While the suggestion make sense, it will not allign with comming changes, since we are planing to add option `--reset-key` https://github.com/TheR1D/shell_gpt/issues/30 which will rewrite a key in the file. In this case it would be difficult to set new env`OPENAI_API_KEY` from Python process, because environment variables exist in a per-process memory space.

**Comment by loiccoyle** [comment]
>  In this case it would be difficult to set new envOPENAI_API_KEY from Python process, because environment variables exist in a per-process memory space.

But you don't need to set a new environment variable. The way I see it is if the user has the `OPENAI_API_KEY` variable set then it indicates that the user is managing their key and `shell_gpt` should simply look it up. 

This PR doesn't break the current implementation of prompting and writing it to file if the variable is not set. So I think the upcoming `--reset-key` option can simply work as expected, and do nothing if the env var is set (maybe show a relevant warning/error msg). What do you think ?

I opened this PR because I use a few chatgpt integrations (https://github.com/not-poma/lazyshell, https://github.com/not-poma/lazyshell) and they all read the `OPENAI_API_KEY` and I was surprised when `shell_gpt` didn't.

**Comment by TheR1D** [comment]
I meant `--reset-key` doesn't make sense when you can't change a key in env, but I agree that it can workout with some warning message. Please add changes in `README.md`, metion the optional env api key setup in [Installation](https://github.com/TheR1D/shell_gpt#installation) section.

**Comment by TheR1D** [comment]
@eric-glb These changes might be interesting for you 🙂 We would be able to pass `OPENAI_API_KEY` as env to the container.

**Review by TheR1D — CHANGES_REQUESTED** [review]
Please add changes in README.md, metion the optional env api key setup in [Installation](https://github.com/TheR1D/shell_gpt#installation) section.

**Comment by loiccoyle** [comment]
> As a client, why do I need such a vulnerability in this software? I still don't believe this change is necessary implementation.
> 
> `--reset-key` is a better alternative in situations where you would like to control API directly.

What vulnerability? Writing an active API key to an unencrypted file?

**Comment by loiccoyle** [comment]
> Please add changes in README.md, metion the optional env api key setup in [Installation](https://github.com/TheR1D/shell_gpt#installation) section.

Sounds good, I'll do it shortly.

**Comment by TheR1D** [comment]
This is a common way to store keys on the system. And it doesn't cancel implementation of `--reset-key`.

**Review by TheR1D — APPROVED** [review]

**Comment by eric-glb** [comment]
> @eric-glb These changes might be interesting for you 🙂 We would be able to pass `OPENAI_API_KEY` as env to the container.

I'll manage the docker part.

**Comment by loiccoyle** [comment]
FYI: I already added the instructions to the readme.

**Comment by TheR1D** [comment]
> From my understanding it's just a small amendment to add in the README.md.

I would remove api key volume, and use env variable instead. Plus README.md updates.

**Comment by eric-glb** [comment]
#63, feel free to modify as you wish ^^

**Pull request merged**
