### PR TITLE
Codespaces

### PR DESCRIPTION
**Pull request by jsburckhardt**
## what

- feat(devcontainer): add devcontainer for codespaces

## why

- codespaces allow you to run devcontainers avoiding the need for virtual environments. If you run your code in a container venv is not required.
- You can get the same environment locally in your machine.

image
image

## How to test

- open vscode in the devcontianer
image
- run ```./pre-push.sh``` to validate tests
image

### CODE REVIEW

**Comment by jsburckhardt** [comment]
happy to add the devcontainer outside of this branch. Currently I'm working on the flow to integrate Azure Open AI and having that env ready saves lots of time. Cheers

**Comment by TheR1D** [comment]
Thank you for the PR.
I think your branch is out of sync, since you are changing all these unrelated files.

**Comment by jsburckhardt** [comment]
Cool, sync the fork and should be up to date. Do you prefer me to add this one against main and create a separate issue?

**Comment by TheR1D** [comment]
Could you please point this PR to the main branch?

**Comment by TheR1D** [comment]
Hi @jsburckhardt,
Due to the rapid development of ShellGPT and recent changes in codespaces, the current implementation in this PR is no longer compatible. With these developments in mind, I will be closing this PR. Thank you for your effort and understanding.

**Pull request closed without merging**
