### PR TITLE
feat(azure): add config to work with azure openai. #203

### PR DESCRIPTION
**Pull request by jsburckhardt**
## What

- feat(azure): add config to work with azure openai. #203
- fix(test_code): update to compare with string

## test results
- create `.env` file with 
  ```bash
  OPENAI_API_TYPE="azure"
  OPENAI_API_HOST="https://<your env>.openai.azure.com
  AZURE_OPENAI_ENGINE="<deployment id>"
  OPENAI_API_KEY="<the key>"
  ```

image

### CODE REVIEW

**Review by TheR1D — CHANGES_REQUESTED** [review]
Could you please provide a test in [test_integration.py](https://github.com/TheR1D/shell_gpt/blob/main/tests/test_integration.py). Also some instructions how to get Azue API key.

**Comment by jsburckhardt** [comment]
Hmm the test results from the image are the integration tests running against azure endpoint. Would you like some tests to validate the API url ?

**Comment by mwester117** [comment]
Hello, upvote to integrate this feature in the next release!

**Comment by TheR1D** [comment]
Hey @jsburckhardt thank you for effort and interest. Since there are a lot of LLM providers, ShellGPT will be using [LiteLLM](https://github.com/BerriAI/litellm) to cover multiple LLM providers. It was implemented in https://github.com/TheR1D/shell_gpt/pull/463 and released as 1.3.0. Given that, I'll pass on this, but thanks for the effort! 🍰

**Pull request closed without merging**
