### PR TITLE
Experimental interactive execution environment. 

### PR DESCRIPTION
**Pull request by lpurdy01**
# Concept
I wanted a way for gpt-4 for ask to execute a command on my system. This way it can help install software, read files, search for what it needs, and accomplish any information gathering / debugging necessary to accomplish things in the terminal. 

It can even pull simple web pages and parse them for information.

# Implementation 
I don't feel good about it, but I went for recursive. 

## What is this on top of?
Also this pull is on top of my current main https://github.com/lpurdy01/shell_gpt, so it probably won't merge without a lot of my versions of leading features also merging in. 

This pull includes:

#85 
#86, but I like #93 @Sakahs version better, and hope it gets merged into main soon so we can standardize.
#92 

## How it works
The big attempt of this update is for the code to recognize when a shell command inside of comments should be run, and to instruct gpt that it can ask to run commands and expect the result in return.

Command given to gpt-4:
```
$ cat sgpt/app.py | sgpt --chat explain_updates --model gpt-4 "Can you write a mermaid diagram compatible with github markdown for how the --interactive-execute argument works?"
```
Here is a Mermaid diagram compatible with GitHub-flavored Markdown that shows how the `--interactive-execute` argument works in the given shell-gpt script.

Please note that to render Mermaid diagrams in your GitHub Markdown file, you may want to install a browser extension like "GitHub+Mermaid" available for Google Chrome and other web browsers. This extension adds support for Mermaid diagrams and will render those diagrams for you inside GitHub pages.

```mermaid
sequenceDiagram
participant User
participant ShellGPT
participant AIAssistant
participant CommandLine
User->>ShellGPT: Run with --interactive-execute
ShellGPT->>AIAssistant: Generate response using role & prompt
AIAssistant->>ShellGPT: Return the completion
ShellGPT->>User: Display command (if any)
User->>ShellGPT: Confirm to execute command
ShellGPT->>CommandLine: Execute command
CommandLine->>ShellGPT: Return stdout and stderr
ShellGPT->>User: Display command result
User->>ShellGPT: Confirm & provide input to continue
ShellGPT->>AIAssistant: Generate response using new prompt
AIAssistant->>ShellGPT: Return the updated completion
User->>ShellGPT: Edit input (optional)
ShellGPT->>User: Continue with updated prompt
```

Here, the interaction flow is represented sequentially between the following participants:

1. User: The person using the shell-gpt interface.
2. ShellGPT: The primary shell-gpt script, handling input and processing requests.
3. AIAssistant: The AI-powered ChatGPT that provides completions for the given prompts.
4. CommandLine: Represents the command line where the shell commands are executed.

## Why recursive
Because it was easy. 
It did require the creation of an `execute_core()` function. This is simply called when another prompt process is started. . 
For now it usually doesn't get too far before hitting an error and crashing, so I'm not too concerned about the memory issues of recursion.

# How to use it:

## Setup
1. Clone branch
2. Run remove_config.sh
3. Run update_package.sh

## Using
To use this simply include an `--interactive-execute` flag in the normal way you would build a command. I recommend naming your chat, but if you don't it will simply name it  `chat = "interactive-execute" + str(os.getpid())` because `--interactive-execute` requires a chat to function. 

It is also recommended to use gpt-4 with this. gpt-3.5 looses focus very quickly and isn't nearly as good at following instructions or identifying when it doesn't know something and needs to run a test.

Here is a sample conversation of it checking the weather:
```
$ sgpt --chat update_system --model gpt-4 --interactive-execute "Could you figure out what the weather is today in Fairbanks Alaska?"
Sure! I will use `curl` to fetch the weather information from `wttr.in`, which provides weather information in a friendly format for the terminal. Please run the following command:

```curl wttr.in/Fairbanks``` 

This command will show you the current weather in Fairbanks, Alaska. You can also append `?format=%C+%t` at the end of the URL to receive a more concise output, like this:

```curl wttr.in/Fairbanks?format=%C+%t```
The assistant has requested to run the following command: ```curl wttr.in/Fairbanks``` 
 (Respond n to enter another prompt) 
 Run? [y/N]: y
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed

0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
Weather report: Fairbanks
45  8652   45  3945    0     0    679      0  0:00:12  0:00:05  0:00:07   809

Overcast
     .--.     28(23) °F
  .-(    ).   ↓ 2 mph
 (___.__)__)  9 mi
0.0 in
┌─────────────┐
┌──────────────────────────────┬───────────────────────┤  Sun 26 Mar ├───────────────────────┬──────────────────────────────┐
│            Morning           │             Noon      └──────┬──────┘     Evening           │             Night            │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│               Overcast       │               Overcast       │               Cloudy         │               Overcast       │
│      .--.     6(0) °F        │      .--.     19(12) °F      │      .--.     28(23) °F      │      .--.     21 °F          │
│   .-(    ).   ↙ 3-7 mph      │   .-(    ).   ← 3-4 mph      │   .-(    ).   ↖ 3-4 mph      │   .-(    ).   ↖ 1-3 mph      │
│  (___.__)__)  6 mi           │  (___.__)__)  6 mi           │  (___.__)__)  6 mi           │  (___.__)__)  6 mi           │
│               0.0 in | 0%    │               0.0 in | 0%    │               0.0 in | 0%    │               0.0 in | 0%    │
└──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘
┌─────────────┐
┌──────────────────────────────┬───────────────────────┤  Mon 27 Mar ├───────────────────────┬──────────────────────────────┐
│            Morning           │             Noon      └──────┬──────┘     Evening           │             Night            │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│  _`/"".-.     Patchy light s…│               Cloudy         │      .-.      Moderate snow  │      .-.      Heavy snow     │
│   ,\_(   ).   21(17) °F      │      .--.     26(23) °F      │     (   ).    32(30) °F      │     (   ).    28(21) °F      │
│    /(___(__)  ← 2-3 mph      │   .-(    ).   ↖ 3-4 mph      │    (___(__)   ↗ 3-4 mph      │    (___(__)   ↗ 6-11 mph     │
│      *  *  *  6 mi           │  (___.__)__)  6 mi           │    * * * *    3 mi           │    * * * *    1 mi           │
│     *  *  *   0.0 in | 0%    │               0.0 in | 0%    │   * * * *     0.0 in | 0%    │   * * * *     0.0 in | 0%    │
└──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘
┌─────────────┐
┌──────────────────────────────┬───────────────────────┤  Tue 28 Mar ├───────────────────────┬──────────────────────────────┐
│            Morning           │             Noon      └──────┬──────┘     Evening           │             Night            │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│    \  /       Partly cloudy  │    \  /       Partly cloudy  │    \  /       Partly cloudy  │               Mist           │
│  _ /"".-.     17(8) °F       │  _ /"".-.     21(12) °F      │  _ /"".-.     24(23) °F      │  _ - _ - _ -  12(6) °F       │
│    \_(   ).   ↗ 7-12 mph     │    \_(   ).   ↗ 8-9 mph      │    \_(   ).   → 1-2 mph      │   _ - _ - _   ↙ 2-4 mph      │
│    /(___(__)  6 mi           │    /(___(__)  6 mi           │    /(___(__)  6 mi           │  _ - _ - _ -  1 mi           │
│               0.0 in | 0%    │               0.0 in | 0%    │               0.0 in | 0%    │               0.0 in | 0%    │
100  8652  100  8652    0     0   1489      0  0:00:05  0:00:05 --:--:--  2233
Would you like to continue the conversation with the following prompt (If you would like to edit input reply 'n' then 'y'): 
"""
Command executed: curl wttr.in/Fairbanks
Return code: 
0
Result stdout: 
Weather report: Fairbanks

                Overcast
       .--.     28(23) °F      
    .-(    ).   ↓ 2 mph        
   (___.__)__)  9 mi           
                0.0 in         
                                                       ┌─────────────┐                                                       
┌──────────────────────────────┬───────────────────────┤  Sun 26 Mar ├───────────────────────┬──────────────────────────────┐
│            Morning           │             Noon      └──────┬──────┘     Evening           │             Night            │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│               Overcast       │               Overcast       │               Cloudy         │               Overcast       │
│      .--.     6(0) °F        │      .--.     19(12) °F      │      .--.     28(23) °F      │      .--.     21 °F          │
│   .-(    ).   ↙ 3-7 mph      │   .-(    ).   ← 3-4 mph      │   .-(    ).   ↖ 3-4 mph      │   .-(    ).   ↖ 1-3 mph      │
│  (___.__)__)  6 mi           │  (___.__)__)  6 mi           │  (___.__)__)  6 mi           │  (___.__)__)  6 mi           │
│               0.0 in | 0%    │               0.0 in | 0%    │               0.0 in | 0%    │               0.0 in | 0%    │
└──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘
                                                       ┌─────────────┐                                                       
┌──────────────────────────────┬───────────────────────┤  Mon 27 Mar ├───────────────────────┬──────────────────────────────┐
│            Morning           │             Noon      └──────┬──────┘     Evening           │             Night            │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│  _`/"".-.     Patchy light s…│               Cloudy         │      .-.      Moderate snow  │      .-.      Heavy snow     │
│   ,\_(   ).   21(17) °F      │      .--.     26(23) °F      │     (   ).    32(30) °F      │     (   ).    28(21) °F      │
│    /(___(__)  ← 2-3 mph      │   .-(    ).   ↖ 3-4 mph      │    (___(__)   ↗ 3-4 mph      │    (___(__)   ↗ 6-11 mph     │
│      *  *  *  6 mi           │  (___.__)__)  6 mi           │    * * * *    3 mi           │    * * * *    1 mi           │
│     *  *  *   0.0 in | 0%    │               0.0 in | 0%    │   * * * *     0.0 in | 0%    │   * * * *     0.0 in | 0%    │
└──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘
                                                       ┌─────────────┐                                                       
┌──────────────────────────────┬───────────────────────┤  Tue 28 Mar ├───────────────────────┬──────────────────────────────┐
│            Morning           │             Noon      └──────┬──────┘     Evening           │             Night            │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│    \  /       Partly cloudy  │    \  /       Partly cloudy  │    \  /       Partly cloudy  │               Mist           │
│  _ /"".-.     17(8) °F       │  _ /"".-.     21(12) °F      │  _ /"".-.     24(23) °F      │  _ - _ - _ -  12(6) °F       │
│    \_(   ).   ↗ 7-12 mph     │    \_(   ).   ↗ 8-9 mph      │    \_(   ).   → 1-2 mph      │   _ - _ - _   ↙ 2-4 mph      │
│    /(___(__)  6 mi           │    /(___(__)  6 mi           │    /(___(__)  6 mi           │  _ - _ - _ -  1 mi           │
│               0.0 in | 0%    │               0.0 in | 0%    │               0.0 in | 0%    │               0.0 in | 0%    │

Result stderr: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
 45  8652   45  3945    0     0    679      0  0:00:12  0:00:05  0:00:07   809
100  8652  100  8652    0     0   1489      0  0:00:05  0:00:05 --:--:--  2233
"""

Continue? [y/N]: y
Here is the current weather report for Fairbanks, Alaska:

Weather report: Fairbanks

                Overcast
      .--.     28(23) °F      
  .-(    ).    ↓ 2 mph        
 (___.__)__)   9 mi           
                0.0 in 

The weather in Fairbanks is overcast, with a temperature of 28°F (feels like 23°F), wind from the south at 2 mph, 9 miles visibility, and no precipitation.

You can also see the weather forecast for the following days in the full output you received. Keep in mind that this information might change, so it's a good idea to check the weather again closer to the time you need the information.
```

# Known Problems

It needs a better prompting, it takes a few commands being executed before it figures out that it has access to a user that will run commands.

There are some weird bugs with command applications that need to prompt the user further. `sudo` works fine on my system, but dnf doesn't show up as doing anything at all. Although later on gpt-4 figured out that it just needed to run dnf commands with -y. 

It doesn't like to `ls` or check if commands that it executed worked correctly enough.

I haven't tried it for writing and executing Python code yet, but theoretically it can do that directly.

### CODE REVIEW

**Comment by joeytwiddle** [comment]
Cool idea! I like how it's safe ... until someone bypasses the safety step!

**Comment by joeytwiddle** [comment]
See also:

https://github.com/Torantulino/Auto-GPT

I think they are using a similar approach.

**Comment by lpurdy01** [comment]
Yep, Auto-GPT was what I was expecting to happen. 

I have switched most of my focus to learning LangChain and llama-index, so I can contribute to projects with a more experimental approach on the AI model and prompting side. 

I also think this project needs some more community focus before it can really take off. A `web docs`, `contribution guide`, and `Discord` would make a big difference.

I would love to hop on a voice channel and chat about what direction @TheR1D wanted to take development at some point. 

Also just have to say, LangChain's Discord with a [kapa.ai](https://www.kapa.ai/) channel is amazing! The concept of switching the `docs` into just a vector database queryable knowledgebase for an AI model that actually knows what is going on is a paradigm shift. "smart docs"

**Comment by krishpop** [comment]
Could something like this be used to interactively run a python script, grok the stdout, and interact/send KeyboardInterrupts? 

For instance, `cat train.py | sgpt run train.py with config config.yaml until the model converges to a performance of 0.2, and then run <ctrl-C> to interrupt`

**Comment by TheR1D** [comment]
Hey @lpurdy01 thank you for the interest and effort!
I'm closing this pull request due to inactivity. Should you decide to resume work on this issue in the future, please don't hesitate to reopen the request or create a new one.

**Pull request closed without merging**
